{% set name = "idyntree" %}
{% set version = "13.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/idyntree/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0acbd2675cf3bb5c5cac56391bb6665a5ac92418863671c4a97a6b7cadffeac1

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - sed  # [unix]
    - diffutils  # [unix]
    - m2-sed  # [win]
    - m2-diffutils  # [win]
    - swig
  host:
    - libxml2
    - ipopt
    - eigen
    - glfw
    - irrlicht
    - python
    - numpy
    - libosqp
    - osqp-eigen
    - assimp
    - libgl-devel  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxfixes  # [linux]
  run:
    - python

test:
  commands:
    - test -f ${PREFIX}/include/iDynTree/KinDynComputations.h  # [not win]
    - test -f ${PREFIX}/lib/libidyntree-core.so  # [linux]
    - test -f ${PREFIX}/lib/libidyntree-core.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/iDynTree/iDynTreeConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\iDynTree\\KinDynComputations.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\idyntree-core.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\idyntree-core.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\iDynTree\\iDynTreeConfig.cmake exit 1  # [win]
    - test $(pip list | grep idyntree | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1  # [unix]
    - pip check
    - cmake-package-check iDynTree
  imports:
    - idyntree
  requires:
    - pip
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/robotology/idyntree
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multibody Dynamics Library designed for Free Floating Robots.

extra:
  recipe-maintainers:
    - traversaro
