schema_version: 1

context:
  name: idyntree
  version: 13.4.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/robotology/idyntree/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 757f3c19d8d30601011f265d48fe050cc1f297ea8c03f06fdf9d2176db3c2fd4

build:
  number: 3

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - if: unix
      then: sed
    - if: unix
      then: diffutils
    - if: win
      then: m2-sed
    - if: win
      then: m2-diffutils
    - swig
  host:
    - libxml2
    - ipopt
    - eigen
    - glfw
    - irrlicht
    - python
    - numpy
    - libosqp
    - osqp-eigen
    - assimp
    - if: linux
      then: libgl-devel
    - if: linux
      then: xorg-libx11
    - if: linux
      then: xorg-libxrandr
    - if: linux
      then: xorg-libxfixes
  run:
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x') }}

tests:
  - python:
      imports:
        - idyntree
  - requirements:
      run:
        - pip
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - if: not win
        then: test -f ${PREFIX}/include/iDynTree/KinDynComputations.h
      - if: linux
        then: test -f ${PREFIX}/lib/libidyntree-core.so
      - if: osx
        then: test -f ${PREFIX}/lib/libidyntree-core.dylib
      - if: not win
        then: test -f ${PREFIX}/lib/cmake/iDynTree/iDynTreeConfig.cmake
      - if: win
        then: if not exist %PREFIX%\\Library\\include\\iDynTree\\KinDynComputations.h exit 1
      - if: win
        then: if not exist %PREFIX%\\Library\\lib\\idyntree-core.lib exit 1
      - if: win
        then: if not exist %PREFIX%\\Library\\bin\\idyntree-core.dll exit 1
      - if: win
        then: if not exist %PREFIX%\\Library\\lib\\cmake\\iDynTree\\iDynTreeConfig.cmake exit 1
      - if: unix
        then: test $(pip list | grep idyntree | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1
      - pip check
      - cmake-package-check iDynTree

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multibody Dynamics Library designed for Free Floating Robots.
  homepage: https://github.com/robotology/idyntree

extra:
  recipe-maintainers:
    - traversaro
